//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumlarID { get; set; }
        public string YorumBaslik { get; set; }
        public string YorumIcerik { get; set; }
        public Nullable<System.DateTime> YorumTarihi { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> BegenmeSayisi { get; set; }
        public Nullable<int> MakaleID { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    }
}
